version: "3.9"

services:
  redis:
    image: redis:${REDIS_IMAGE_TAG}
    volumes:
      - deffie_hellman_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
  auth:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    networks:
      - default
      - deffie_hellman_network

volumes:
  deffie_hellman_data:
networks:
  default:
  deffie_hellman_network:
    name: deffie_hellman_network