version: "3.9"

services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  server:
    build: .
    depends_on:
      - redis
    ports:
      - "5052:5052"
    restart: always

volumes:
  redis-data: