version: "3.9"

services:
  redis:
    image: redis:${REDIS_IMAGE_TAG}
    volumes:
      - deffie_hellman_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5

  server:
    build: .
    depends_on:
      - redis
    ports:
      - "5052:5052"
    restart: always

volumes:
  deffie_hellman_data:
networks:
  deffie_hellman_network: