// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "grpc/authpb.proto",
    "version": "version not set"
  },
  "paths": {
    "/auth/dh": {
      "post": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_reqDHParams",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/authDHreqDHParamsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHreqDHParamsResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    },
    "/auth/is_valid_authkey/{authkey}": {
      "get": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_isValidAuthkey",
        "parameters": [
          {
            "type": "string",
            "name": "authkey",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHIsValidAuthKeyResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    },
    "/auth/pq": {
      "post": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_reqPQ",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/authDHReqPQRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHReqPQResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "authDHIsValidAuthKeyResponse": {
      "type": "object",
      "properties": {
        "isValid": {
          "type": "boolean"
        }
      }
    },
    "authDHReqPQRequest": {
      "type": "object",
      "properties": {
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        }
      }
    },
    "authDHReqPQResponse": {
      "type": "object",
      "properties": {
        "g": {
          "type": "string",
          "format": "uint64"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "p": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "authDHreqDHParamsRequest": {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "authDHreqDHParamsResponse": {
      "type": "object",
      "properties": {
        "b": {
          "type": "string"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "type_url": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "runtimeError": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        },
        "error": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "grpc/authpb.proto",
    "version": "version not set"
  },
  "paths": {
    "/auth/dh": {
      "post": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_reqDHParams",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/authDHreqDHParamsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHreqDHParamsResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    },
    "/auth/is_valid_authkey/{authkey}": {
      "get": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_isValidAuthkey",
        "parameters": [
          {
            "type": "string",
            "name": "authkey",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHIsValidAuthKeyResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    },
    "/auth/pq": {
      "post": {
        "tags": [
          "AuthService"
        ],
        "operationId": "AuthService_reqPQ",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/authDHReqPQRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/authDHReqPQResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/runtimeError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "authDHIsValidAuthKeyResponse": {
      "type": "object",
      "properties": {
        "isValid": {
          "type": "boolean"
        }
      }
    },
    "authDHReqPQRequest": {
      "type": "object",
      "properties": {
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        }
      }
    },
    "authDHReqPQResponse": {
      "type": "object",
      "properties": {
        "g": {
          "type": "string",
          "format": "uint64"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "p": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "authDHreqDHParamsRequest": {
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "authDHreqDHParamsResponse": {
      "type": "object",
      "properties": {
        "b": {
          "type": "string"
        },
        "messageId": {
          "type": "string",
          "format": "uint64"
        },
        "nonce": {
          "type": "string"
        },
        "serverNonce": {
          "type": "string"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "type_url": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "runtimeError": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        },
        "error": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
