// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/my/repo/models"
)

// AuthServiceReqDHParamsOKCode is the HTTP code returned for type AuthServiceReqDHParamsOK
const AuthServiceReqDHParamsOKCode int = 200

/*
AuthServiceReqDHParamsOK A successful response.

swagger:response authServiceReqDHParamsOK
*/
type AuthServiceReqDHParamsOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthDHreqDHParamsResponse `json:"body,omitempty"`
}

// NewAuthServiceReqDHParamsOK creates AuthServiceReqDHParamsOK with default headers values
func NewAuthServiceReqDHParamsOK() *AuthServiceReqDHParamsOK {

	return &AuthServiceReqDHParamsOK{}
}

// WithPayload adds the payload to the auth service req d h params o k response
func (o *AuthServiceReqDHParamsOK) WithPayload(payload *models.AuthDHreqDHParamsResponse) *AuthServiceReqDHParamsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth service req d h params o k response
func (o *AuthServiceReqDHParamsOK) SetPayload(payload *models.AuthDHreqDHParamsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthServiceReqDHParamsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AuthServiceReqDHParamsDefault An unexpected error response.

swagger:response authServiceReqDHParamsDefault
*/
type AuthServiceReqDHParamsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RuntimeError `json:"body,omitempty"`
}

// NewAuthServiceReqDHParamsDefault creates AuthServiceReqDHParamsDefault with default headers values
func NewAuthServiceReqDHParamsDefault(code int) *AuthServiceReqDHParamsDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthServiceReqDHParamsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auth service req d h params default response
func (o *AuthServiceReqDHParamsDefault) WithStatusCode(code int) *AuthServiceReqDHParamsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auth service req d h params default response
func (o *AuthServiceReqDHParamsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auth service req d h params default response
func (o *AuthServiceReqDHParamsDefault) WithPayload(payload *models.RuntimeError) *AuthServiceReqDHParamsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth service req d h params default response
func (o *AuthServiceReqDHParamsDefault) SetPayload(payload *models.RuntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthServiceReqDHParamsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
