// Code generated by go-swagger; DO NOT EDIT.

package auth_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewAuthServiceIsValidAuthkeyParams creates a new AuthServiceIsValidAuthkeyParams object
//
// There are no default values defined in the spec.
func NewAuthServiceIsValidAuthkeyParams() AuthServiceIsValidAuthkeyParams {

	return AuthServiceIsValidAuthkeyParams{}
}

// AuthServiceIsValidAuthkeyParams contains all the bound params for the auth service is valid authkey operation
// typically these are obtained from a http.Request
//
// swagger:parameters AuthService_isValidAuthkey
type AuthServiceIsValidAuthkeyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Authkey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAuthServiceIsValidAuthkeyParams() beforehand.
func (o *AuthServiceIsValidAuthkeyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAuthkey, rhkAuthkey, _ := route.Params.GetOK("authkey")
	if err := o.bindAuthkey(rAuthkey, rhkAuthkey, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthkey binds and validates parameter Authkey from path.
func (o *AuthServiceIsValidAuthkeyParams) bindAuthkey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Authkey = raw

	return nil
}
