// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthDHreqDHParamsResponse auth d hreq d h params response
//
// swagger:model authDHreqDHParamsResponse
type AuthDHreqDHParamsResponse struct {

	// b
	B string `json:"b,omitempty"`

	// message Id
	MessageID string `json:"messageId,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// server nonce
	ServerNonce string `json:"serverNonce,omitempty"`
}

// Validate validates this auth d hreq d h params response
func (m *AuthDHreqDHParamsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth d hreq d h params response based on context it is used
func (m *AuthDHreqDHParamsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthDHreqDHParamsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthDHreqDHParamsResponse) UnmarshalBinary(b []byte) error {
	var res AuthDHreqDHParamsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
