// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthDHreqDHParamsRequest auth d hreq d h params request
//
// swagger:model authDHreqDHParamsRequest
type AuthDHreqDHParamsRequest struct {

	// a
	A string `json:"a,omitempty"`

	// message Id
	MessageID string `json:"messageId,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// server nonce
	ServerNonce string `json:"serverNonce,omitempty"`
}

// Validate validates this auth d hreq d h params request
func (m *AuthDHreqDHParamsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth d hreq d h params request based on context it is used
func (m *AuthDHreqDHParamsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthDHreqDHParamsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthDHreqDHParamsRequest) UnmarshalBinary(b []byte) error {
	var res AuthDHreqDHParamsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
