// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthDHReqPQResponse auth d h req p q response
//
// swagger:model authDHReqPQResponse
type AuthDHReqPQResponse struct {

	// g
	G string `json:"g,omitempty"`

	// message Id
	MessageID string `json:"messageId,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// p
	P string `json:"p,omitempty"`

	// server nonce
	ServerNonce string `json:"serverNonce,omitempty"`
}

// Validate validates this auth d h req p q response
func (m *AuthDHReqPQResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth d h req p q response based on context it is used
func (m *AuthDHReqPQResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthDHReqPQResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthDHReqPQResponse) UnmarshalBinary(b []byte) error {
	var res AuthDHReqPQResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
