// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthDHIsValidAuthKeyResponse auth d h is valid auth key response
//
// swagger:model authDHIsValidAuthKeyResponse
type AuthDHIsValidAuthKeyResponse struct {

	// is valid
	IsValid bool `json:"isValid,omitempty"`
}

// Validate validates this auth d h is valid auth key response
func (m *AuthDHIsValidAuthKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth d h is valid auth key response based on context it is used
func (m *AuthDHIsValidAuthKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthDHIsValidAuthKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthDHIsValidAuthKeyResponse) UnmarshalBinary(b []byte) error {
	var res AuthDHIsValidAuthKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
