// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthDHReqPQRequest auth d h req p q request
//
// swagger:model authDHReqPQRequest
type AuthDHReqPQRequest struct {

	// message Id
	MessageID string `json:"messageId,omitempty"`

	// nonce
	Nonce string `json:"nonce,omitempty"`
}

// Validate validates this auth d h req p q request
func (m *AuthDHReqPQRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth d h req p q request based on context it is used
func (m *AuthDHReqPQRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthDHReqPQRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthDHReqPQRequest) UnmarshalBinary(b []byte) error {
	var res AuthDHReqPQRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
